services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/aitask
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=fa4a6aeab03a9b8bc455ed7a19b422c2c922bd9233fc877e275fc6a4cffbc5a89bd41ce9a3dae27f516e8af77d42b4a788c769b815f8992bdd5d002efc3249b8
    depends_on:
      - mongodb
      - redis
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    restart: always

  worker:
    build: ./worker
    environment:
      - MONGO_URI=mongodb://mongodb:27017/aitask
      - REDIS_URL=redis://redis:6379
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongodb
      - redis
    restart: always

volumes:
  mongo_data:
